[develop]
script_dir=$base/lib/niihan_description

[install]
install_scripts=$base/lib/niihan_description

[options.data_files]
share/ament_index/resource_index/packages =
    resource/niihan_description
share/niihan_description =
    package.xml
share/niihan_description/urdf =
    urdf/niihan.urdf.xacro
share/niihan_description/worlds =
    worlds/niihan_patrol_base.world
